### ISSUE TITLE
How to keep "media_url https" field content?

### ISSUE THREAD

**Issue by 4xx** [n3mo/json2csv#1]
Convert JSON to CSV, how to keep "media_url https" field content?
Thank you!

```
  "media": [
    {
      "id": 661332071969906688,
      "id_str": "661332071969906688",
      "indices": [
        11,
        34
      ],
      "media_url": "http://pbs.twimg.com/media/CS2GA_xW4AAvxBo.png",
      "media_url_https": "https://pbs.twimg.com/media/CS2GA_xW4AAvxBo.png",
      "url": "https://t.co/XRVRmtmGxd",
      "display_url": "pic.twitter.com/XRVRmtmGxd",
      "expanded_url": "http://twitter.com/aiww/status/661332072099901440/photo/1",
      "type": "photo",
```

**Comment by n3mo** [comment]
Thanks for bringing this to my attention. You've helped to reveal a problem with how jsan handles array data in JSON. I'm working on a patch and will hopefully have a fix posted soon. Stay tuned...

**Comment by n3mo** [comment]
I've fixed the problem. The prior version (1.3.0) had limited support for nested arrays in JSON. You should now be able to retrieve your data field as expected:

``` sh
jsan -i mydata.json -k entities:media:media_url_https
```

Or, equivalently:

``` sh
cat mydata.json | jsan -k entities:media:media_url_https
```

This fix is implemented in version 1.4.0 of jsan, which is available for Linux at the [usual download location](http://www.nicholasvanhorn.com/software). I'll post Mac OS X binaries tomorrow when I get access to my Mac.

Cheers!

**Comment by 4xx** [comment]
Great! Thank you so much!

**Comment by n3mo** [comment]
You're welcome--and thanks for the feedback! I've compiled the Mac OS X binaries and made them available.
Cheers!
